image: eve-lisp
org: evecitry
network: yes
config:
  binds:
    - /dev:/dev
    - /etc/resolv.conf:/etc/resolv.conf
    - /run:/run
    - /persist:/persist
  net: host
  capabilities:
    - all
  pid: host
