image: eve-spdk
org: lfedge
network: yes
config:
  binds:
    - /dev:/dev
    - /dev/pts:/dev/pts
    - /run:/run
    - /config:/config
    - /persist:/persist
    - /lib/modules:/lib/modules
  net: host
  capabilities:
    - all
